#! /bin/bash

# tbg - terminal background in Xfce
# 
# Alternates between white and black
# background colors

terminalrc=~/.config/Terminal/terminalrc
light_color=ffffffffffff
dark_color=000000000000

if grep "ColorBackground=#${light_color}" $terminalrc >/dev/null; then
    sed -i -e "s/\(ColorBackground=#\)${light_color}/\1${dark_color}/" \
           -e "s/\(ColorForeground=#\)${dark_color}/\1${light_color}/" $terminalrc
else
    sed -i -e "s/\(ColorForeground=#\)${light_color}/\1${dark_color}/" \
           -e "s/\(ColorBackground=#\)${dark_color}/\1${light_color}/" $terminalrc
fi
